name: Refresh SGX Companies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 1 * *' # At 21:00 on the 1st day of every month (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install uv (Python package manager)
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
            uv sync --frozen

      - name: Run scraper 
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          uv run python -m src.refresh_sgx_companies 

      - name: Pull Latest Changes
        run: git pull origin main

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "refresh sgx_companies.json" --allow-empty)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}